DROP TABLE ACCEPT_TABLE;
DROP TABLE INSTRUCTIONS_TABLE;
DROP TABLE PROC_INSTRUCTIONS_TABLE;
DROP TABLE PROC_INSTRUCTIONS_DETAIL_TABLE;
DROP TABLE PROCESS_STATUS_TABLE;
DROP TABLE WORK_GROUP_STATUS_TABLE;
DROP TABLE WORK_RESULT_TABLE;
DROP TABLE AI_RELATION_TABLE;
DROP TABLE MATERIAL_GROUP_TABLE;
DROP TABLE INSTRUCTIONS_MASTER;
DROP TABLE PROC_INSTRUCTIONS_MASTER;
DROP TABLE PROC_INSTRUCTIONS_DETAIL_MASTER;
DROP TABLE PROCESS_MASTER;
DROP TABLE WORK_GROUP_MASTER;
DROP TABLE WORK_MASTER;
DROP TABLE STATUS_MASTER;
DROP TABLE USER_MASTER;


CREATE TABLE ACCEPT_TABLE(
MATERIAL_NO TEXT NOT NULL ,
MATERIAL_NAME TEXT ,
CATEGORY_NO TEXT ,
MANUFACTURER TEXT ,
QTY TEXT ,
STORAGE TEXT ,
LOT_NO TEXT ,
EXP_DATE TEXT ,
USER_LOT_NO TEXT ,
STORAGE_LOCATION TEXT ,
REQUIRED_AMOUNT TEXT ,
PREPARED_AMOUNT TEXT ,
QA_APP_STATUS TEXT ,
STATUS TEXT ,
PRIMARY KEY(MATERIAL_NO)
);


CREATE TABLE INSTRUCTIONS_TABLE(
BATCH_ID TEXT NOT NULL ,
IM_ID TEXT ,
NAME TEXT ,
COMMENT TEXT ,
CELL_TYPE TEXT ,
INPUT_AMOUNT TEXT ,
TARGET_AMOUNT_CELLS TEXT ,
TARGET_AMOUNT_BAGS TEXT ,
TOTAL_PASSAGE_TIMES TEXT ,
DURATION_EST TEXT ,
MEDIUM TEXT ,
ECM_COATING TEXT ,
DISSOCIATION_REAGENT TEXT ,
PRE_CULTURE_VESSEL TEXT ,
PRE_CULTURE_MATERIAL_NAME TEXT ,
PRE_CULTURE_VOLUME TEXT ,
PRE_CULTURE_INCUBATION_TIME TEXT ,
ICP1_VESSEL TEXT ,
ICP1_MATERIAL_NAME TEXT ,
ICP1_VOLUME TEXT ,
ICP1_INCUBATION_TIME TEXT ,
ICP2_VESSEL TEXT ,
ICP2_MATERIAL_NAME TEXT ,
ICP2_VOLUME TEXT ,
ICP2_INCUBATION_TIME TEXT ,
ICP3_VESSEL TEXT ,
ICP3_MATERIAL_NAME TEXT ,
ICP3_VOLUME TEXT ,
ICP3_INCUBATION_TIME TEXT ,
PROTOCOL TEXT ,
STARTING_TIME TEXT ,
FINISH_TIME TEXT ,
PRE_CULTURE_KIT_RT_LABEL TEXT ,
PRE_CULTURE_KIT_P4T_LABEL TEXT ,
PRE_CULTURE_KIT_M20T_LABEL TEXT ,
PRE_CULTURE_COUNT TEXT ,
EX_CULTURE_KIT_RT_LABEL TEXT ,
EX_CULTURE_KIT_P4T_LABEL TEXT ,
EX_CULTURE_KIT_M20T_LABEL TEXT ,
STATUS TEXT ,
PRIMARY KEY(BATCH_ID)
);


CREATE TABLE PROC_INSTRUCTIONS_TABLE(
BATCH_ID TEXT NOT NULL ,
INS_PROC_ID TEXT NOT NULL ,
RECIPE_NAME TEXT ,
CELL_TYPE TEXT ,
TARGET_AMOUNT TEXT ,
INCUBATION TEXT ,
END_POINT TEXT ,
COMMENT TEXT ,
PRIMARY KEY(BATCH_ID,INS_PROC_ID)
);


CREATE TABLE PROC_INSTRUCTIONS_DETAIL_TABLE(
BATCH_ID TEXT NOT NULL ,
INS_PROC_ID TEXT NOT NULL ,
INS_PROC_DETAIL_ID TEXT NOT NULL ,
ITEM_CONDITION TEXT ,
MATERIAL_NO_NAME TEXT ,
REQUIRED_QUANTITY TEXT ,
USER_LOT_NO TEXT ,
CAPTURE TEXT ,
PRIMARY KEY(BATCH_ID,INS_PROC_ID,INS_PROC_DETAIL_ID)
);


CREATE TABLE PROCESS_STATUS_TABLE(
BATCH_ID TEXT NOT NULL ,
PROCESS_ID TEXT NOT NULL ,
STATUS TEXT ,
PRIMARY KEY(BATCH_ID,PROCESS_ID)
);


CREATE TABLE WORK_GROUP_STATUS_TABLE(
BATCH_ID TEXT NOT NULL ,
PROCESS_ID TEXT NOT NULL ,
WORK_GROUP TEXT NOT NULL ,
STATUS TEXT ,
PRIMARY KEY(BATCH_ID,PROCESS_ID,WORK_GROUP)
);


CREATE TABLE WORK_RESULT_TABLE(
WORK_RESULT_NO TEXT NOT NULL ,
PROCESS_ID TEXT ,
WORK_GROUP TEXT ,
WORK_ID TEXT ,
ID TEXT ,
CHECK_RESULT TEXT ,
CHECK_REASON TEXT ,
CHECK_COA TEXT ,
CHECK_COA_REASON TEXT ,
CHECK_FILE_NAME TEXT ,
CHECK_FILE_BASE64 TEXT ,
LABEL TEXT ,
COUNT_RESULT TEXT ,
WORK_USERID TEXT ,
WORK_USERNAME TEXT ,
WORK_DATE TEXT ,
PRIMARY KEY(WORK_RESULT_NO)
);


CREATE TABLE AI_RELATION_TABLE(
IM_ID TEXT NOT NULL ,
PROCESS_ID TEXT NOT NULL ,
MATERIAL_NO TEXT NOT NULL ,
PRIMARY KEY(IM_ID,PROCESS_ID,MATERIAL_NO)
);


CREATE TABLE MATERIAL_GROUP_TABLE(
MATERIAL_GORUP_ID TEXT NOT NULL ,
MATERIAL_NO TEXT NOT NULL ,
PRIMARY KEY(MATERIAL_GORUP_ID,MATERIAL_NO)
);


CREATE TABLE INSTRUCTIONS_MASTER(
IM_ID TEXT NOT NULL ,
NAME TEXT ,
COMMENT TEXT ,
CELL_TYPE TEXT ,
INPUT_AMOUNT TEXT ,
TARGET_AMOUNT_CELLS TEXT ,
TARGET_AMOUNT_BAGS TEXT ,
TOTAL_PASSAGE_TIMES TEXT ,
DURATION_EST TEXT ,
MEDIUM TEXT ,
ECM_COATING TEXT ,
DISSOCIATION_REAGENT TEXT ,
PRE_CULTURE_VESSEL TEXT ,
PRE_CULTURE_MATERIAL_NAME TEXT ,
PRE_CULTURE_VOLUME TEXT ,
PRE_CULTURE_INCUBATION_TIME TEXT ,
ICP1_VESSEL TEXT ,
ICP1_MATERIAL_NAME TEXT ,
ICP1_VOLUME TEXT ,
ICP1_INCUBATION_TIME TEXT ,
ICP2_VESSEL TEXT ,
ICP2_MATERIAL_NAME TEXT ,
ICP2_VOLUME TEXT ,
ICP2_INCUBATION_TIME TEXT ,
ICP3_VESSEL TEXT ,
ICP3_MATERIAL_NAME TEXT ,
ICP3_VOLUME TEXT ,
ICP3_INCUBATION_TIME TEXT ,
MATERIAL_GORUP_ID TEXT ,
PROTOCOL TEXT ,
PRIMARY KEY(IM_ID)
);


CREATE TABLE PROC_INSTRUCTIONS_MASTER(
IM_ID TEXT NOT NULL ,
INS_PROC_ID TEXT NOT NULL ,
RECIPE_NAME TEXT ,
CELL_TYPE TEXT ,
TARGET_AMOUNT TEXT ,
INCUBATION TEXT ,
END_POINT TEXT ,
COMMENT TEXT ,
PRIMARY KEY(IM_ID,INS_PROC_ID)
);


CREATE TABLE PROC_INSTRUCTIONS_DETAIL_MASTER(
IM_ID TEXT NOT NULL ,
INS_PROC_ID TEXT NOT NULL ,
INS_PROC_DETAIL_ID TEXT NOT NULL ,
ITEM_CONDITION TEXT ,
MATERIAL_NO_NAME TEXT ,
REQUIRED_QUANTITY TEXT ,
USER_LOT_NO TEXT ,
CAPTURE TEXT ,
PRIMARY KEY(IM_ID,INS_PROC_ID,INS_PROC_DETAIL_ID)
);


CREATE TABLE PROCESS_MASTER(
PROCESS_ID TEXT NOT NULL ,
PROCESS_NAME TEXT ,
PRIMARY KEY(PROCESS_ID)
);


CREATE TABLE WORK_GROUP_MASTER(
PROCESS_ID TEXT NOT NULL ,
WORK_GROUP TEXT NOT NULL ,
WORK_GROUP_NAME TEXT ,
BEFORE_WORK_GROUP TEXT ,
STATUS TEXT ,
DISPLAY_TYPE TEXT ,
PRIMARY KEY(PROCESS_ID,WORK_GROUP)
);


CREATE TABLE WORK_MASTER(
PROCESS_ID TEXT NOT NULL ,
WORK_GROUP TEXT NOT NULL ,
WORK_ID TEXT NOT NULL ,
WORK TEXT ,
AUTHORITY TEXT ,
CAPTURE1 TEXT ,
CAPTURE2 TEXT ,
CAPTURE3 TEXT ,
CAPTURE4 TEXT ,
CAPTURE5 TEXT ,
CSV1 TEXT ,
CSV2 TEXT ,
CSV3 TEXT ,
CSV4 TEXT ,
CSV5 TEXT ,
PRIMARY KEY(PROCESS_ID,WORK_GROUP,WORK_ID)
);


CREATE TABLE STATUS_MASTER(
TABLE_TYPE TEXT NOT NULL ,
STATUS_CODE TEXT NOT NULL ,
STATUS_NAME TEXT ,
PRIMARY KEY(TABLE_TYPE,STATUS_CODE)
);


CREATE TABLE USER_MASTER(
USERID TEXT NOT NULL ,
USERNAME TEXT ,
PASSWORD TEXT ,
AUTHORITY TEXT ,
PRIMARY KEY(USERID)
);


